apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-api
  template:
    metadata:
      labels:
        app: quote-api
    spec:
      containers:
      - name: quote-api
        image: ghcr.io/abker-ranim/quote-api-devops/quote-api:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"